---
language: perl
perl:
  - '5.22'
  - '5.20'
  - '5.18'
sudo: false
before_install:
  - |
      f_install_navel_dep() {
          local cpanm_chain=()

          for dep in "${@}" ; do
              cpanm_chain+=("https://github.com/navel-it/${dep}")
          done

          cpanm --quiet --installdeps --notest "${cpanm_chain[@]}" && \
          cpanm --quiet "${cpanm_chain[@]}"
      }
  - f_install_navel_dep navel-base
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
after_success:
  - cover -test -report coveralls
notifications:
  email: false
