---
language: perl
perl:
  - '5.22'
  - '5.20'
  - '5.18'
sudo: false
before_install:
  - |
      f_install_navel_dep() {
          local repo_url

          for dep in "${@}" ; do
              repo_url="https://github.com/navel-it/${dep}.git"

              cpanm --quiet --installdeps --notest "${repo_url}" && \
              cpanm --quiet "${repo_url}"
          done
      }
  - f_install_navel_dep navel-base
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
after_success:
  - cover -test -report coveralls
notifications:
  email: false
